# this Kubernetes cluster configuration.
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

managedNodeGroups:
  - name: expense-mng
    instanceType: m5.large
    desiredCapacity: 3
    #spot: true         ## we can use this spot instances for lower cost but no guarantee for the instances(nodes) availability.
    ## it is recommended to use the odd number of nodes in the EKS cluster like 3,5,7, etc.
    ## refer: https://etcd.io/docs/v3.3/faq/#what-is-failure-tolerance
    
